"""Render the consolidated payload as an agent context document (markdown).

This resurrects the original purpose of the user's adf_distill.py: a compact,
front-loaded markdown distillation of a factory, written for an LLM agent's
context window rather than a human's browser. Same analysis, same honesty
rules as every other renderer — one payload, four renderings.

Design rules for this format:
* Orientation first: what this factory is, what may be claimed, what's
  missing — before any detail, so a truncated read still orients correctly.
* Tables over prose; every fact scannable and greppable.
* Token-conscious: queries truncated, config strings squeezed, no repetition.
  A rough token estimate is printed at the end of generation.
* Machine-recoverable lineage: the endpoint contract is emitted per entity so
  an agent (or the future bi-lineage-join) can join without re-parsing.
"""

from __future__ import annotations

from pathlib import Path

QUERY_CHARS = 600          # per-activity query budget in the agent doc


def _cell(s) -> str:
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ").strip() or "—"


def _tbl(headers, rows) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(_cell(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def _join(items, sep=", ", empty="—"):
    items = [str(i) for i in items if i]
    return sep.join(items) if items else empty


def _clip(s, n):
    s = s or ""
    return s if len(s) <= n else s[:n].rstrip() + " …[truncated]"


def build_agent_md(payload: dict) -> str:
    fac = payload["factory"]
    ents = {e["key"]: e for e in payload["entities"]}
    lbl = lambda k: ents.get(k, {}).get("label", k)
    lbls = lambda ks: _join(lbl(k) for k in ks)
    L = []
    w = L.append

    # ---- orientation ----------------------------------------------------
    w(f"# ADF factory: {payload['title']}")
    w("")
    w(f"> Agent context generated by adf-doc-gen on {payload['generated']}. "
      f"Mode: **{payload['mode']}**. Everything below is design-time truth "
      f"derived statically from JSON: no run history; parameter and Key Vault "
      f"secret *names* only, never values; hops into notebooks/procs/external "
      f"services are marked `opaque` (lineage past them is unknown, not absent); "
      f"`dynamic` targets are runtime-built and the static name is indicative "
      f"only; \"unreferenced\" claims are scoped to this factory — external "
      f"invocation (REST, Synapse, Logic Apps) is invisible.")
    w("")
    w(f"Counts: {fac['pipelineCount']} pipelines · {fac['activityCount']} activities · "
      f"{fac['dataflowCount']} data flows · {fac['datasetCount']} datasets · "
      f"{fac['linkedServiceCount']} linked services · {fac['triggerCount']} triggers · "
      f"{fac['entityCount']} data entities · {fac['lineageEdgeCount']} movement edges · "
      f"{fac['unresolvedCount']} unresolved refs · {fac['warningCount']} warnings.")
    w("")

    det = {k: v for k, v in (payload.get("details") or {}).items() if v}
    if det:
        w("Factory details: " + "; ".join(f"{k}: {v}" for k, v in det.items()))
        w("")
    cov = payload.get("coverage") or {}
    if cov:
        w(f"Coverage: input {_join(cov.get('inputFormats', []))}; "
          f"{cov.get('skippedFiles', 0)} unreadable file(s); "
          f"{cov.get('unresolvedReferences', 0)} missing reference(s); "
          f"{cov.get('opaqueActivities', 0)} of {cov.get('activities', 0)} activities opaque; "
          f"{cov.get('dynamicActivities', 0)} resolved at runtime; "
          f"{cov.get('unknownFootprints', 0)} with unknown footprint; "
          f"{payload.get('redactions', 0)} secret value(s) withheld. Run history: not available.")
        w("")

    missing = [r for r in payload["resolution"] if r["status"] == "MISSING"]
    if missing:
        w("## MISSING INPUTS (analysis incomplete — export these next)")
        w(_tbl(["kind", "name", "impact", "referenced by"],
               [[r["kind"], r["name"], r["impact"], _join(r["referencedBy"][:3], "; ")]
                for r in missing]))

    # ---- warnings up front ----------------------------------------------
    w("## Warnings (read before acting)")
    if payload["warnings"]:
        w(_tbl(["sev", "category", "detail"],
               [[x["severity"], x["category"], x["message"]] for x in payload["warnings"]]))
    else:
        w("Nothing flagged.\n")

    # ---- orchestration --------------------------------------------------
    w("## Orchestration")
    if payload["triggers"]:
        w(_tbl(["trigger", "type", "state", "starts", "schedule/event"],
               [[t["name"], t["type"], t["state"], _join(t["startsPipelines"]),
                 t["detail"]] for t in payload["triggers"]]))
        w("A trigger not in state `Started` does not fire.\n")
    else:
        w("No triggers supplied — how these pipelines start is invisible here.\n")

    kids = {}
    for e in payload["orchestration"]["edges"]:
        kids.setdefault((e["fromKind"], e["from"]), []).append(e)

    def tree(kind, name, depth, seen):
        pad = "  " * depth
        mark = {"trigger": "⏰", "pipeline": "▶", "dataflow": "≋"}.get(kind, "•")
        exists = (kind != "pipeline" or any(p["name"] == name for p in payload["pipelines"])) \
                 and (kind != "dataflow" or any(d["name"] == name for d in payload["dataflows"]))
        suffix = "" if exists else "  (NOT SUPPLIED)"
        if (kind, name) in seen:
            w(f"{pad}- {mark} {name} ↺ (expanded above)")
            return
        seen.add((kind, name))
        w(f"{pad}- {mark} {name}{suffix}")
        for e in kids.get((kind, name), []):
            tree(e["toKind"], e["to"], depth + 1, seen)

    w("Call tree (triggers, then entry points):")
    w("")
    seen: set = set()
    for t in payload["triggers"]:
        tree("trigger", t["name"], 0, seen)
    for p in payload["pipelines"]:
        if p["entryPoint"]:
            tree("pipeline", p["name"], 0, seen)
    w("")

    # ---- pipelines ------------------------------------------------------
    w("## Pipelines")
    for p in payload["pipelines"]:
        w(f"### {p['name']}")
        bits = [f"Role: {p['roleLine']}"]
        started = p["triggers"] + p["invokedBy"]
        bits.append("Started by: " + (_join(started) if started
                    else "nothing in this factory (may be invoked externally)"))
        if p["invokes"]:
            bits.append("Invokes: " + _join(p["invokes"]))
        if p["dataflows"]:
            bits.append("Data flows: " + _join(p["dataflows"]))
        if p["parameters"]:
            bits.append("Params: " + _join(f"{k}({v})" for k, v in p["parameters"].items()))
        w(". ".join(bits) + ".")
        if p["description"]:
            w(f"_{p['description']}_")
        inc = (f" **(incomplete — not supplied: {_join(p['effectiveIncomplete'])})**"
               if p["effectiveIncomplete"] else "")
        w(f"- Effective reads{inc}: {lbls(p['effectiveReads'])}")
        w(f"- Effective writes{inc}: {lbls(p['effectiveWrites'])}")
        w("")
        rows = []
        for a in p["activities"]:
            flags = []
            if a.get("dynamic"): flags.append("dynamic")
            if a.get("opaque"): flags.append("opaque")
            if a.get("inactive"): flags.append("INACTIVE")
            if a["category"] in ("movement", "transform") and not a.get("retry"):
                flags.append("no-retry")
            err = [d for d in a["dependsOn"] if d["on"] and d["on"] != "Succeeded"]
            for d in err:
                flags.append(f"on:{d['activity']}[{d['on']}]")
            rows.append(["↺" if a["step"] == 0 else a["step"],
                         a["activity"] + ("" if a["scope"] == "(root)" else f" ⟨{a['scope']}⟩"),
                         a["type"], lbls(a["reads"]), lbls(a["writes"]),
                         _join(flags, " ", "")])
        w(_tbl(["#", "activity ⟨scope⟩", "type", "reads", "writes", "flags"], rows))
        queries = [(a["activity"], a["query"]) for a in p["activities"] if a.get("query")]
        for name, q in queries:
            w(f"Query in `{name}`:")
            w("```sql")
            w(_clip(q, QUERY_CHARS))
            w("```")
        w("")

    # ---- data flows -----------------------------------------------------
    if payload["dataflows"]:
        w("## Data flows")
        for df in payload["dataflows"]:
            w(f"### {df['name']}")
            w(f"Sources: {_join(s['dataset'] or s['label'] for s in df['sources'])}. "
              f"Sinks: {_join(s['dataset'] or s['label'] for s in df['sinks'])}. "
              f"Used by: {_join(df['usedBy'], '; ')}.")
            w(_tbl(["#", "step", "op", "inputs", "note"],
                   [[s["execOrder"] or "?", s["name"], s["op"], _join(s["inputs"], "; "),
                     "DEAD END" if s["deadEnd"] else ""]
                    for s in sorted(df["steps"], key=lambda s: s["execOrder"] or 10**6)]))
            for t in df["sinkTraces"]:
                w(f"- Trace `{t['sink']}` ← {_join(t['sources'])}: "
                  + " → ".join(t["chain"]))
            w("")

    # ---- lineage --------------------------------------------------------
    w("## Data movement lineage")
    w(_tbl(["sources", "sinks", "via", "pipeline::activity", "flags"],
           [[_join(lbl(k) for k in e["sources"]), _join(lbl(k) for k in e["sinks"]),
             e["mechanism"], f"{e['pipeline']}::{e['activity']}",
             _join([x for x in ["opaque" if e["opaque"] else "",
                                "dynamic" if e["dynamic"] else ""] if x], " ", "")]
            for e in payload["lineageEdges"]]))
    movers = [e for e in payload["entities"] if e["upstream"] or e["downstream"]]
    w("Transitive closure (blast-radius lookup):")
    w(_tbl(["entity", "kind", "depends on (all upstream)", "feeds (all downstream)"],
           [[e["label"], e["kind"],
             _join((lbl(k) for k in e["upstream"]), "; ", "root"),
             _join((lbl(k) for k in e["downstream"]), "; ", "terminal")]
            for e in movers]))

    # ---- resources ------------------------------------------------------
    if payload["datasets"]:
        w("## Datasets")
        rows = []
        for d in payload["datasets"]:
            ep = d["endpoint"]
            target = _join([f"{ep['schema']}.{ep['object']}" if ep["schema"] and ep["object"]
                            else ep["object"],
                            "/".join(x for x in [ep["container"], ep["path"]] if x) or None,
                            ep["url"]], " · ") if any(ep.values()) else d["display"]
            notes = []
            if d["dynamic"]: notes.append("dynamic")
            if d["parameterized"]: notes.append("params: " + _join(d["parameters"]))
            if d["unreferenced"]: notes.append("UNREFERENCED in this factory")
            rows.append([d["name"], d["type"], d["linkedService"], target,
                         _join(notes, "; ", "")])
        w(_tbl(["dataset", "type", "linked service", "resolves to", "notes"], rows))

    if payload["linkedServices"]:
        w("## Linked services (names, never secrets)")
        rows = []
        for ls in payload["linkedServices"]:
            notes = []
            if ls["keyVault"]: notes.append(ls["auth"] or "Key Vault")
            if ls["inlineCredential"]: notes.append("INLINE CREDENTIAL flagged (value not shown)")
            if ls["parameterized"]: notes.append("params: " + _join(ls["parameters"]))
            if ls["unreferenced"]: notes.append("UNREFERENCED")
            rows.append([ls["name"], ls["system"],
                         _join([ls["server"], ls["database"], ls["url"]], " · "),
                         _join(notes, "; ", "")])
        w(_tbl(["linked service", "system", "target", "notes"], rows))

    # ---- entity endpoint contract ---------------------------------------
    w("## Entity endpoints (cross-tool lineage contract)")
    w("Fields: system/server/database/schema/object/path/url/container — "
      "join key with pbi-doc-gen partition sources.")
    rows = []
    for e in payload["entities"]:
        ep = {k: v for k, v in e["endpoint"].items() if v}
        rows.append([e["label"], e["kind"], _join(e["roles"], "; "),
                     _join(f"{k}={v}" for k, v in ep.items()),
                     _join(e["aliases"], "; ", "")])
    w(_tbl(["entity", "kind", "roles", "endpoint", "aliases"], rows))

    return "\n".join(L) + "\n"


def render_agent_md(payload: dict, out_path: str | Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = build_agent_md(payload)
    out_path.write_text(text, encoding="utf-8")
    return out_path


def estimate_tokens(text: str) -> int:
    """Rough token estimate (≈4 chars/token) so agents can budget."""
    return max(1, len(text) // 4)
