"""Legacy HTML import (handoff section 4): known engine HTML without a manifest.

The native payload is recovered without evaluating any script: the page must carry
exactly one `const DATA = ` literal, decoded as JSON, and the engine's own metadata
element. Only supported native schemas convert. The result is a new shared-profile
artifact regenerated by the trusted renderer; the original bytes are not kept.
"""
from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass

from . import __version__
from .build import NotPublishable, build_artifact
from .convert import SUPPORTED_NATIVE_SCHEMAS, UnsupportedProjection
from .identity import environment_key

_MARKER = re.compile(rb"\bconst DATA = ")
_ENGINE_ELEMENTS = {b'id="pbi-documentation-metadata"': "power_bi", b'id="adf-documentation-details"': "adf"}
_NATIVE = {"power_bi": "pbi-doc-gen", "adf": "adf-doc-gen"}
METADATA_FIELDS = ("title", "description", "tags", "business_area", "environment", "owner")
DETAILS_NOT_KEPT = ("Details entered in the original file (report location, connection account references, "
                    "factory details) are not carried over; record them in the library instead.")


@dataclass(frozen=True)
class LegacyIdentity:
    document_id: str
    asset_id: str
    stored_in: str = "library"


def extract(html: bytes):
    """Return (document_type, native payload) or raise UnsupportedProjection."""
    engines = {v for k, v in _ENGINE_ELEMENTS.items() if k in html}
    hits = list(_MARKER.finditer(html))
    if len(engines) != 1 or len(hits) != 1:
        raise UnsupportedProjection("this HTML is not a recognised Power BI or Data Factory document")
    document_type = engines.pop()
    try:
        text = html.decode("utf-8")
        data, _ = json.JSONDecoder().raw_decode(text, len(html[:hits[0].end()].decode("utf-8")))
    except (UnicodeDecodeError, ValueError):
        raise UnsupportedProjection("the document's data could not be read") from None
    if not isinstance(data, dict):
        raise UnsupportedProjection("the document's data could not be read")
    native = f"{_NATIVE[document_type]}/{data.get('schemaVersion')}"
    if native not in SUPPORTED_NATIVE_SCHEMAS[document_type]:
        raise UnsupportedProjection(f"no safe projection for native schema {native!r}")
    data.pop("published", None)
    return document_type, data


def parse_metadata(raw) -> dict:
    """legacy_metadata: optional JSON object of catalogue fields for the converted document."""
    if raw in (None, ""):
        return {}
    meta = json.loads(raw) if isinstance(raw, str) else raw
    if not isinstance(meta, dict) or set(meta) - set(METADATA_FIELDS):
        raise ValueError(f"legacy_metadata must be an object with only: {', '.join(METADATA_FIELDS)}")
    for key, value in meta.items():
        ok = (isinstance(value, list) and all(isinstance(t, str) for t in value)) if key == "tags" \
            else isinstance(value, str)
        if not ok:
            raise ValueError(f"legacy_metadata.{key} has the wrong type")
    return meta


def convert(html: bytes, metadata: dict, *, document_id: str | None = None, asset_id: str | None = None,
            environment: str | None = None):
    """(artifact bytes, manifest) for a legacy page; a new stream identity unless one is given."""
    document_type, data = extract(html)
    env_label = environment if environment is not None else metadata.get("environment", "")
    identity = LegacyIdentity(document_id or str(uuid.uuid4()), asset_id or str(uuid.uuid4()))
    try:
        artifact, manifest = build_artifact(
            document_type, data, profile="shared", query_code="withheld", identity=identity,
            environment_key=environment_key(env_label),
            classification={"business_area": metadata.get("business_area", ""), "environment": env_label,
                            "owner": metadata.get("owner", "")},
            title=metadata.get("title") or data.get("title") or "", description=metadata.get("description", ""),
            tags=metadata.get("tags", ()), source_kind="legacy", source_label="Imported legacy HTML",
            generator_version=__version__)
    except NotPublishable as exc:
        raise UnsupportedProjection(str(exc)) from None
    return artifact, manifest
